{{- if .Values.gateway.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclaw.gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openclaw.gateway.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.worker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclaw.worker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openclaw.worker.labels" . | nindent 4 }}
{{- end }}
